version: '3.8'

services:
  site-connect-fibra:
    image: seu-usuario/site-connect-fibra:latest
    networks:
      - network-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
     
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.site-connect-fibra.rule=Host(`seu-dominio.com`)
        - traefik.http.routers.site-connect-fibra.entrypoints=websecure
        - traefik.http.routers.site-connect-fibra.tls.certresolver=letsencrypt
        - traefik.http.services.site-connect-fibra.loadbalancer.server.port=80
        - traefik.http.routers.site-connect-fibra.middlewares=secure-headers
        - traefik.http.middlewares.secure-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE
        - traefik.http.middlewares.secure-headers.headers.accesscontrolalloworigin=*
        - traefik.http.middlewares.secure-headers.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.secure-headers.headers.addvaryheader=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik-public:
    external: true